general:
  run_name: 'canny_lapa'
  out_dir: './out'
  save_path: "${general.out_dir}/${general.run_name}/"
  base_path: "config/exp5_lapa/base.yaml"

dataset:
  # Choose one of the following processing methods:
  # processing: 'grayscale'
  processing: 'canny'
  # processing: 'DoG'
  # processing: 'random'

evaluate:
  model_ckpt: out/canny_LaPa/decoder_epoch10.pt       # path to the .pt you want