general:
  run_name: 'LoG_LaPa'
  out_dir: './out'
  save_path: "${general.out_dir}/${general.run_name}/"
  base_path: "config/exp5_lapa/base.yaml"

# ─── DATASET SELECTION ──────────────────────────────────────
dataset:
  processing: 'LoG'
  LoG: # LOG options
    method: 'cortical'
    kernel_size: 123
    kernel_type: 'log'
    dilation: 1
    padding_mode: 'reflect'
    kde_k: 16
    kde_alpha: 1.0
    beta: 0.55
