general:
  run_name: 'canny_sun'
  out_dir: './out'
  save_path: "${general.out_dir}/${general.run_name}/"
  base_path: "config/exp6_sun/base.yaml"

dataset:
  # Choose one of the following processing methods:
  # processing: 'grayscale'
  processing: 'canny'
  # processing: 'DoG'
  # processing: 'random'

evaluate:
  model_ckpt: out/canny_sun/decoder_epoch02.pt       # path to the .pt you want