general:
  run_name: 'grayscale_sun'
  out_dir: './out'
  save_path: "${general.out_dir}/${general.run_name}/"
  base_path: "config/exp6_sun/base.yaml"

dataset:
  # Choose one of the following processing methods:
  processing: 'grayscale'
  # processing: 'canny'
  # processing: 'LoG'
  # processing: 'random'

evaluate:
  model_ckpt: out/grayscale_sun/decoder_epoch01.pt       # path to the .pt you want