Description:
  model_name: decoder_exp1_debug1

general:
  device: 'cuda:0'
  gpu: 0
  save_path: ./out/LoG_LaPa_debug1/
  project_name: decoder_exp1
  run_name: LoG_LaPa
  entity: michelleappel
  model_log_freq: 16       # how often to log samples/parameters to W&B
  save_every: 1            # epochs between checkpoint saves
  params: './config/params.yaml'  # path to your phosphene simulator params
  n_phosphenes: 1024

simulator:
  use_normalization: True
  base_size: 3
  scale: 0.0001
  A_min: 0.0
  A_max: 0.00016         # match your params['sampling']['stimulus_scale']
  learning_rate: 0.002
  steps: 2000
  target: null           # or a float, if you want to fix the target brightness

dataset:
  dataset: LaPa
  target: ['boundary']   # or ['semantic']
  data_directory: ../data/face/LaPa
  debug_subset: False
  grayscale: False
  circular_mask: False
  imsize: [256, 256]
  processing: 'LoG'      # one of 'grayscale', 'canny', 'LoG', 'random'
  retinal_compression: False
  fov: 16

modulation:
  method: 'cortical'     # 'cortical' or 'kde'
  kernel_size: 123
  kernel_type: 'log'
  dilation: 1
  padding_mode: 'reflect'
  kde_k: 16               # only used if method: 'kde'
  kde_alpha: 1.0          # only used if method: 'kde'

model:
  in_channels: 1
  out_channels: 1
  output_activation: 'sigmoid'

train:
  epochs: 1
  batch_size: 1
  lr: 5e-5
  weight_decay: 1e-5
  num_workers: 0

loss:
  alpha: 0.5
  beta: 0.5
