general:
  device: cuda
  base_path: "config/exp6_sun/base.yaml"

dataset:
  # Choose one of the following processing methods:
  # processing: 'grayscale'
  # processing: 'canny'
  processing: 'LoG'
  # processing: 'random'

evaluate:
  split: test
  model_ckpt: out/LoG_sun/decoder_epoch1.pt       # path to the .pt you want
  metrics:
    - mse
    - ssim
    - vgg_perceptual
    - lpips
  batch_size: 1
  num_workers: 0
  
  timing:
    measure_inference: true
  output:
    results_dir: results/test/                              # where CSV + plots live
    per_image_csv: per_image_metrics.csv                    # raw scores
    summary_csv: summary_metrics.csv                        # mean ± std